### ISSUE TITLE
Thanks! You saved me a bundle of time

### ISSUE THREAD

**Issue by andreas-amlabs** [joakimeriksson/ai-smarthome#2]
Hi

Just wanted to say thanks, you saved me a bundle of time! I guess
our setups are similar and pushing the image over mqtt from the external
tensorflow machine is a great idea.

I had to make some minor fixes
- Updated config to allow for each camera to have its own config (mqtt post)
- Had to make some changes to make the processing work continuously - not really sure why, but  I get some h264 decode error and then processing stops (rtsp closes)

Let me know if I should prep 1 or 2 PRs, my changes are here
https://github.com/andreas-amlabs/ai-smarthome/tree/ai-smarthome-amlabs/yolov3-ha

Moving forward I think I will make more changes, based on your code. I consider the following setup

* HomeAssistant running
* In my setup, HA knows about e.g. "camera line crossing" or "camera motion"
* Based on the above binary sensor trigger, trigger "smartcam.py" to process the image

This will reduce the load on the mqtt bus and also free up time on the tensorflow machine

Again, thanks. Great work !

**Comment by joakimeriksson** [comment]
Great to hear that you used my code and like the setup! I will take a look at your changes and get back - I will in fact work with MQTT and AI/ML tomorrow as we have a research project where I can do a bit more of this - so improvements are welcome!
